spring:
  output.ansi.enabled: always
# TODO add configuration metadata through Java annotations
graphHopper:
  osmFilePath: /app/resources/romania-latest.osm.pbf
  graphCachePath: /data/cache/routing-graph-cache 

nominatim:
  api: http://localhost:8081
messages:
  penalties:
    CATEGORY_0:
        fine-points: 0
        penalty-points: 0
    CATEGORY_1:
        fine-points: 2 to 3
        penalty-points: 2
    CATEGORY_2:
        fine-points: 4 to 5
        penalty-points: 3
    CATEGORY_3:
        fine-points: 6 to 8
        penalty-points: 4
    CATEGORY_4:
        fine-points: 9 to 20
        penalty-points: 6
    CATEGORY_5:
        fine-points: 9 to 20
        penalty-points: until license is suspended
